### ISSUE TITLE
[updater on forks] Notify if there's conflicts needed to fix manually

### ISSUE THREAD

**Issue by AndreiJirohHaliliDev2006** [pokurt/Nana-Remix#17]
If the updater fails because its conflicted some files between the upstream and the fork's code, prompt the user to fix conflicts manually. If they don't have push permissions to the fork, prompt the user to create an issue for maintainers of that fork to fix merge conflicts manually.

---

This issue is related to MR #16.

**Comment by pokurt** [comment]
@AndreiJirohHaliliDev2006 ITS ALREADY DOCUMENTEED RESAAAAD

**Comment by AndreiJirohHaliliDev2006** [comment]
> @AndreiJirohHaliliDev2006 ITS ALREADY DOCUMENTEED RESAAAAD

Yeah, press F.

**Comment by Dank-del** [comment]
Bruwuwh

**Comment by adyatan** [comment]
...

**Comment by pokurt** [comment]
@AndreiJirohHaliliDev2006 in docs ive already said... if you are using heroku. you will need to create a new account... yes im bad at using heroku and i barely even touch it... it uses docker so it clones from my repo... please consider checking Dockerfile for more information about it

**Comment by AndreiJirohHaliliDev2006** [comment]
> @AndreiJirohHaliliDev2006 in docs ive already said... if you are using heroku. you will need to create a new account... yes im bad at using heroku and i barely even touch it... it uses docker so it clones from my repo... please consider checking Dockerfile for more information about it

Okay, I understood. Case closed.
