### ISSUE TITLE
(PYL-W0612) Unused variable found

### ISSUE THREAD

**Issue by baidaadarsh** [pokurt/Nana-Remix#48]
## Description
An unused variable take up space in the code, and can lead to confusions. It should be removed. If this variable is necessary, name the variable `_` or start the name with `unused` or `_unused`.

## Occurrences
There are 2 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/pokurt/Nana-Remix/issue/PYL-W0612/occurrences/](https://deepsource.io/gh/pokurt/Nana-Remix/issue/PYL-W0612/occurrences/)

**Comment by pokurt** [comment]
thanks for linking this. but im more focused on fixing bug the moment. after than when i clean up ill probably replace all unused variables with _
