### ISSUE TITLE
Some Strings in Hebrew are not competible with right to left

### ISSUE THREAD

**Issue by pokurt** [pokurt/Nana-Remix#67]
- a perfect example is here in our translation chat: https://t.me/translation_nanaremix/86

**Comment by iiiiii1wepfj** [comment]
yes this is the problem with rtl languages we need to think how to fix this

**Comment by pokurt** [comment]
> yes this is the problem with rtl languages we need to think how to fix this

found this in bottalk, https://t.me/BotTalk/206616
